[package]
name = "smol-pong-tcp"
version = "0.1.0"
authors = ["Luca Cominardi <luca.cominardi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "1.2.5"
